apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: joise/orders-service
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-service:27017/orders
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLUSTER_ID
              value: atlas
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - name: orders-service
      protocol: TCP
      port: 3000
      targetPort: 3000
