apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: joise/payments-service
          env:
            - name: MONGO_URI
              value: mongodb://payments-mongo-service:27017/payments
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLUSTER_ID
              value: atlas
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - name: payments-service
      protocol: TCP
      port: 3000
      targetPort: 3000
